[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://chat-app-brok.onrender.com"  # or leave out and set via CLI

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
